version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: develop
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: develop
    schedule:
      interval: "monthly"
